### PR TITLE
Fixed #43

### LINKED ISSUE #43: Commands have arguments (so no prompting for everything)
I want to run `/say SE 240 "foo"` and have it say "foo" in room 240 of SE. But right now it errors with a undefined command name.

Maybe split on spaces for command arguments?

### PR DESCRIPTION
**Pull request by The-Quill**

### CODE REVIEW

**Comment by vihanb** [comment]
why are you PRing on your own repo.

**Comment by The-Quill** [comment]
Because I want to keep different branches for different features @vihanb, so that way I can separate each of them and PR (and check/CR them) separately, rather than straight merging.

**Comment by vihanb** [comment]
you can keep your dev branches local and then merge locally so you don't have multiple remote branches for development

**Comment by The-Quill** [comment]
I'd rather multiple remote branches, in an ideal world the concept of open source means others can help out instead of users poking repo owners with a giant stick

**Comment by vihanb** [comment]
ohk

**Pull request merged**
